fix(lilypond): okular has been renamed to kdePackages.okular
Addresses the following error during derivation of the flake.

    error: The top-level okular alias has been removed.

    Please explicitly use kdePackages.okular for the latest Qt 6-based version,
    or libsForQt5.okular for the deprecated Qt 5 version.